
import '../../infostructure/model/name_model.dart';

abstract class AppConst{
  AppConst._();

  static const String bomdod="bomdod";
  static const String peshin="peshin";
  static const String asr="asr";
  static const String shom="shom";
  static const String xufton="xufton";
  static const String vitr="vitr";
  static const String mode="mode";

  static List<NameModel> listOf99Name=[
    NameModel(arabic: "الرحمن", name: "Ar-Rohman", desc: "Mehribon — Ulugʻ neʼmatlarni beruvchi. Bu sifat faqat Allohga xos boʻlib, barchaga kofirga ham, moʻminga ham mehribon va neʼmat beruvchi maʼnosini anglatadi. Rahmon sifatini Alloh taolodan boshqa hech kimga nisbatan ishlatib boʻlmaydi."),
    NameModel(arabic: "الرحيم", name: "Ar-Rohim", desc: "Rahmli — „Rohiym“ latif neʼmatlarni beruvchi. Bu sifat xosroq boʻlib, qiyomat kuni faqat moʻminlarga rahm qiluvchi maʼnosini anglatadi. Va Allohdan oʻzgalarga, jumladan Paygʻambar alayhissalomga nisbatan ham ishlatiladi."),
    NameModel(arabic: "الملك", name: "Al-Malik", desc: "Podsho — Barcha narsani egasi.${"Malik"} haqiqiy egadir.Undan oʻzga ega yoqdir.Shuning uchun bandalar faqat unga qul boʻladilar. Hech vaqtda bir qulga ikki xoʻjayin boʻlmaydi.Shuning uchun insonlar oʻzlariga oʻxshagan insonlarga emas, balki yagona yaratganga, haqiqiy Malikka qul boʻlish lozim."),
    NameModel(arabic: "القدوس", name: "Al-Quddus", desc: "Muqaddas, nuqsonlardan holi — Barcha ayblardan xoli, noloyiq sifatlardan munazzah, mutlaq muqaddaslik va mutlaq poklik Allohning oʻzigagina hosdir."),
    NameModel(arabic: "السلام", name: "As-Salam", desc: "Ofat va balolardan salomat. Qutqarayotgan — „Salom“-barcha nuqsonlardan salomat. Shuningdek, tinchlik, xotirjamlik va rohat beruvchi degani. Alloh „Salom“ sifati ila bandalarga tinchlik, omonlik, xotirjamlik ato qiladi."),
    NameModel(arabic: "المؤمن", name: "Al-Mumin", desc: "Moʻmin-iymon va omonlik beruvchi."),
    NameModel(arabic: "المهيمن", name: "Al-Muhaymin", desc:"Hamma narsani qamrab oluvchi.Alloh bandalarning barcha holatlariga guvoh boʻlib turadi.Undan hech narsa maxfiy qolmaydi." ),
    NameModel(arabic: "العزيز", name: "Al-Aziz", desc: "Izzat va qudrat sohibi. Ulugʻ — Barchaning ustidan gʻolib. Undan biror narsa gʻolib kelolmaydi."),
    NameModel(arabic: "الجبار", name: "Al-Jabbar", desc: "Bandalarini ishlarini isloh etuvchi. Jabbor — oliy qadar ulugʻ, Uning oldida hamma oʻzini xor tutadi."),
    NameModel(arabic: "المتكبر", name: "Al-Mutakabbir", desc: "Kattalik yarashuvchi zot. Mutakabbir — kibriyosi va ulugʻligi behad. Uning oldida boshqalar qul boʻlib turadi."),
    NameModel(arabic: "الخالق", name: "Al-Xoliq", desc:"Yaratuvchi, vujudga keltiruvchi. Xoliq — Asli va oʻxshashi yoq narsaning oʻlchovini mos qilib yaratuvchi. Xoliq mutloq vujudga keltiruvchidir." ),
    NameModel(arabic: "البارئ", name: "Al-Bari", desc: "Bori' — Yoʻqdan paydo qiluvchi, vujudga keltiruvchi, yaratuvchi. Bori’ning vujudga keltirishida tafovut yoqdir."),
    NameModel(arabic: "المصور", name: "Al-Musovvir", desc:"Maxluqot va mavjudotlarga suvrat va shakl beruvchi."),
    NameModel(arabic: "الغفار", name: "Al-G'offar", desc: "Gʻaffor — Koʻplab magʻfirat qilib, bandalarning aybini oʻz fazli ila kechib yuboruvchi. bandalarning aybu nuqsonlari va gunohu maʼsiyatlarini fosh qilmay yopib turuvchi."),
    NameModel(arabic: "القهار", name: "Al-Qohhar", desc: "Qahhor — Barcha maxluqotlarni qabzasida tutib, ularni oʻz hukmiga yuritib va qudrati ila boʻysundirib turuvchi."),
    NameModel(arabic: "الوهاب", name: "Al-Vahhab", desc: "Oʻz neʼmatlarini tekin ato etuvchi."),
    NameModel(arabic: "الرزاق", name: "Ar-Rozzaq", desc: "Barcha tirik mavjudot rizqini yetkazib beruvchi."),
    NameModel(arabic: "الفتاح", name: "Al-Fattah", desc: "Hukm etuvchi, rahmat hazinalarini ochuvchi."),
    NameModel(arabic: "العليم", name: "Al-Alim", desc: "Biluvchi, dono, ilm sohibi. Boʻlgan va boʻladigan, avvalgi va oxirgi, zohir va botin narsalarning barchasini biluvchi."),
    NameModel(arabic: "القابض", name: "Al-Qobiz", desc: "Kimlarningdir rizqini qiyuvchi, ruhlarni qabz etuvchi (oluvchi)."),
    NameModel(arabic: "الباسط", name: "Al-Basit", desc: "Kimlargadir keng rizq beruvchi, ruh baxsh etuvchi."),
    NameModel(arabic: "الخافض", name: "Al-Xofiz", desc: "Kofirlar martabasini tushiruvchi."),
    NameModel(arabic: "الرافع", name: "Ar-Rofi", desc: "Moʻminlar martabasini koʻtaruvchi."),
    NameModel(arabic: "المعز", name: "Al-Mu’izz", desc: "Kimlarnidir aziz, qadrli etuvchi."),
    NameModel(arabic: "المذل", name: "Al-Muzill", desc: "Kimlarnidur xoru zalil qiluvchi."),
    NameModel(arabic: "السميع", name: 'As-Sami', desc: "Maxfiy va oshkora gap va sharpalarni, xatto dildan oʻtganini ham, eshituvchi."),
    NameModel(arabic: "البصير", name: "Al-Basir", desc: "Hamma maxfiy va oshkora narsalarni koʻruvchi."),
    NameModel(arabic: "الحكم", name: "Al-Hakam", desc: "Qatʼiy hukm etuvchi."),
    NameModel(arabic: "العدل", name: "Al-Adi", desc: "Oʻta adolatli."),
    NameModel(arabic: 'اللطيف', name: "Al-Latif", desc: "Bandalariga sezdirmay oʻz lutfu ehsonini yetkasizb beruvchi."),
    NameModel(arabic: "الخبير", name: "Al-Xobir", desc: "Hamma maxfiy va oshkora ishlardan xabardor"),
    NameModel(arabic: "الحليم", name: "Al-Halim", desc: "Jazolashga shoshmaydigan, hilm bilan yaxshilik qilib turuvchi."),
    NameModel(arabic: "العظيم", name: "Al-Azim", desc: "Azamatli va ulugʻ zot. Aql tasavvur qila olmaydigan darajada azamatli va ulugʻ."),
    NameModel(arabic: "الغفور", name: "Al-G'ofur", desc: "Koʻp magʻfirat qiluvchi."),
    NameModel(arabic: "الشكور", name: "Ash-Shakur", desc: "Oʻz amaliga koʻp savob beruvchi."),
    NameModel(arabic: "العلي", name: "Al-Aliyy", desc: "Martabasi oliylikda benihoya."),
    NameModel(arabic: "الكبير", name: "Al-Kabir", desc: "Hammadan ulugʻ."),
    NameModel(arabic: "الحفيظ", name: "Al-Hafiz", desc: "Har bir narsani komil muhofaza qiluvchi."),
    NameModel(arabic: "المقيت", name: "Al-Muqit", desc: "Barcha moddiy va ruhiy rizqlarni yaratuvchi."),
    NameModel(arabic: "الحسيب", name: "An-Hasib", desc: "Hisob qiluvchi, kifoya qiluvchi."),
    NameModel(arabic: "الجليل", name: "Al-Jalil", desc: "Sifatlarida ulugʻlikka ega."),
    NameModel(arabic: "الكريم", name: "Al-Karim", desc: "Saxovatli va karami keng. Birov soʻramasa ham, hech bir evaz olmasdan, narsalarni ato qiluvchi. Qarama-qarshilikdan pok. Karamli ishlar va xislatlar sohibi."),
    NameModel(arabic: "الرقيب", name: "Ar-Roqib", desc: "Doimo kuzatib turuvchi. Raqiyb — hech bir zararni ham qoʻymay tekshirib turuvchi."),
    NameModel(arabic: "المجيب", name: "Al-Mujib", desc: "Duolarni ijobat qiluvchi."),
    NameModel(arabic: "الواسع", name: "Al-Vasi", desc: "Keng va keng qamrovli zotdir"),
    NameModel(arabic: "الحكيم", name: "Al-Hakim", desc: "Dono"),
    NameModel(arabic: "الودود", name: "Al-Vadud", desc: "Bandalarini sevuvchi"),
    NameModel(arabic: "المجيد", name: "Al-majid", desc: "Eng ulugʻvor"),
    NameModel(arabic: "الباعث", name: "Al-Bais", desc: "Oʻliklarning tiriltiruvchisi"),
    NameModel(arabic: "الشهيد", name: "Ash-Shahid", desc: "Har bir narsaga hoziru nozir. Barchaga shohidlik beruvchi."),
    NameModel(arabic: "الحق", name: "Al-Haqq", desc: "Oʻzgarmas sobit zot. Haqni yuzaga chiqaruvchi zot."),
    NameModel(arabic: "الوكيل", name: "Al-Vakil", desc: "Barchaning ishi unga topshirilgan zot."),
    NameModel(arabic: "القوى", name: "Al-Qovviyy", desc: "Quvvatli zot."),
    NameModel(arabic: "المتين", name: "Al-Matin", desc: "Matonatli zot."),
    NameModel(arabic: "الولى", name: "Al-Valiyy", desc: "Himoya qiluvchi doʻst, homiy va yordamchi"),
    NameModel(arabic: "الحميد", name: "Al-Hamid", desc: "Barcha maqtovlar ila maqtalgan zot."),
    NameModel(arabic: "المحصى", name: "Al-Muhsi", desc: "Barcha narsaning hisobini olgan zot."),
    NameModel(arabic: "المبدئ", name: "Al-Mubid", desc: "Barcha narsalarni avval boshdan bor qilgan zot."),
    NameModel(arabic: "المعيد", name: "Al-Muidi", desc: "Yoʻq boʻlgan narsalarni yana qaytadan bor qiluvchi."),
    NameModel(arabic: "المحيى", name: "Al-Muhyi", desc: "Tiriltiruvchi. U zot oʻliklarni tiriltiruvchidir va bu ismga ularni tiriltirishdan oldin sazovordir. Uni ularni oʻlik boʻlganlaridan keyin jon kiritib tirik qilganidan keyin tiriltiruvchi, deb atalganidek, ularni xalq qilishdan oldin, ularga hayot berishidan oldin ham, tiriltiruvchi, deyilaveradi. Xuddi, xaloyiqni xalq qilishidan oldin Xoliq boʻlganidek."),
    NameModel(arabic: "المميت", name: "Al-Mumit", desc: "Oʻldirivchi. Barcha jonzotlarning jonini oluvchi."),
    NameModel(arabic: "الحي", name: "Al-Hayy", desc: "Tirik. U tirikdir, oʻlmas. Yaʼni, Allohning hayoti abadiydir, oʻlim ila yoʻq boʻlmas. Shuningdek, Allohning hayoti azaliydir, oldindan yoʻq boʻlgan emas."),
    NameModel(arabic: "القيوم", name: "Al-Qoyyum", desc: "Oʻz oʻzidan qoim boʻlgan va boshqalarni qoim qilgan zot."),
    NameModel(arabic: "الواجد", name: "Al-Vajid", desc: "Topuvchi. Xohlagan narsasini topuvchi. Bu ishda birov Uni toʻsa olmaydi."),
    NameModel(arabic: "الماجد", name: "Al-Majid", desc: "Majdu sharaf sohibi boʻlgan zot."),
    NameModel(arabic: "الواحد", name: "Al-Vahid", desc: "Yagona. Bita. Boʻlinmas. U zot oʻz zotida ham, sifatlarida ham va ishlarida ham birdir."),
    NameModel(arabic: "الصمد", name: "Al-Ahad", desc: "Yagona, Boʻlinmas."),
    NameModel(arabic: "الصمد", name: "As-Somad", desc: "Somad sifati koʻp maʼnolarni oʻz ichiga oladi:- itoat qilingan ulugʻ-Usiz hech bir ish bitmaydi.- hech kimga hojati tushmaydi, barchaning hojati Unga tushadi.- butun maxluqot bitib tugasa ham, Oʻzi doim boqiydir va hokazo."),
    NameModel(arabic: "القادر", name: "Al-Qodir", desc: "Cheksiz qudrat sohibi. U zot har bir narsaga qodirdir. har bir ish unga osondir."),
    NameModel(arabic: "المقتدر", name: "Al-Muqtadir", desc: "Juda ham qudratli."),
    NameModel(arabic: "المقدم", name: "Al-Muqoddim", desc: "Oldinga suruvchi. U zot xohlagan shaxs va narsani xohlaganidan oldinga suradi."),
    NameModel(arabic: "المؤخر", name: "Al-Mu'axxir", desc: "Orqaga suruvchi. U zot xohlagan shaxs va narsani xohlaganidan orqaga suradi."),
    NameModel(arabic: "الأول", name: "Al-Avval", desc: "„Avval“ — U hamma narsadan avval, yaʼni, barcha mavjudotlar yoʻqligida Alloh bor edi. Mavjudotlarni „Avval“ sifatiga ega boʻlgan Alloh yaratdi. Yaʼni, Alloh vujudga kelishining boshlanishi yoʻqdir."),
    NameModel(arabic: "الأخر", name: "Al-Axir", desc: "„Oxir“ — U hamma narsa yoʻq boʻlib ketganda ham Oʻzi qoladi."),
    NameModel(arabic: "الظاهر", name: "Az-Zohir", desc: "„Zohir“ — Uning mavjudligi oshkor, ochiq-oydindir. U hamma narsadan zohir-ustundir."),
    NameModel(arabic: "الباطن", name: "Al-Batin", desc: "${"Botin"} — U koʻzga koʻrinmaydi. Hammadan pinhon-maxfiy narsalarni bilib turuvchidir."),
    NameModel(arabic: "الوالي", name: "Al-Vali", desc: "Har bir narsaga voliy — ega boʻlgan zot."),
    NameModel(arabic: "المتعالي", name: "Al-Mutā'ali", desc: "Nuqsonlardan yuqori turuvchi zot."),
    NameModel(arabic: "البر", name: "Al-Barr", desc: "Ulugʻ yaxshilik qiluvchi."),
    NameModel(arabic: "التواب", name: "At-Tavvab", desc: "Bandalarni tavbaga yoʻllovchi va ularning tavbasini koʻplab qabul qiluvchi zot."),
    NameModel(arabic: "المنتقم", name: "Al-Muntaqim", desc: "Zolim va osiylardan intiqom oluvchi."),
    NameModel(arabic: "العفو", name: "Al-Afuvv", desc: "Afv qiluvchi."),
    NameModel(arabic: "الرؤوف", name: "Ar-Rouf", desc: "Oʻta shafqatli va mehribon."),
    NameModel(arabic: "مالك الملك", name: "Mālik-ul-Mulk", desc: "Mulk egasi. Bu dunyodagi ishlarni oʻzi xohlaganicha qiladi. Uning qazosini qaytaradigan va hukmini oʻzgartiradigan yoʻq."),
    NameModel(arabic: "ذو الجلال والإكرام", name: "Zūl-Jalālival’ikrom", desc: "Sharaf va kamol egasi. Karam va ikrom egasi."),
    NameModel(arabic: "المقسط", name: "Al-Muqsiţ", desc: "Oʻz adolati ila mazlumlarga nusrat va zolimlarga jazo beruvchi."),
    NameModel(arabic: "	ar|الجامع}}", name: "Al-Jami", desc: "Jamlovchi. Barcha haqiqatlarni jamlovchi. Odamlarni qiyomat kuni jamlovchi."),
    NameModel(arabic: "الغني", name: "Al-G'oni", desc: "Behojat. Uning hech kim va hech narsaga hojati tushmaydi."),
    NameModel(arabic: "المغني", name: "Al-Mug'ni", desc: "Behojat qiluvchi. U zot Oʻz bandalaridan qay birini xohlasa behojat qilib qoʻyadi."),
    NameModel(arabic: "المانع", name: "Al-Mani", desc: "Man qiluvchi."),
    NameModel(arabic: "الضار", name: "Az-Zorr", desc: "Zarar qiluvchi. Zararli narsalarni ham yaratuvchi."),
    NameModel(arabic: "النافع", name: "An-Nāfi", desc: "Manfaat beruvchi."),
    NameModel(arabic: "النور", name: "An-Nur", desc: "Oʻz-oʻzi ila zohir boʻlgan va oʻzgalarni zohir qilgan."),
    NameModel(arabic: "الهادي", name: "Al-Hādi", desc: "Hidoyat qiluvchi. U zot Oʻz fazli ila xohlagan kimsani hidoyat qiladi. Yaʼni, Alloh kimni toʻgʻri yoʻlga hidoyat qilsa, albatta, Oʻz xohishi va fazli ila hidoyat qiladi."),
    NameModel(arabic: "البديع", name: "Al-Badi", desc: "Oʻxshashi yoʻq narsalarni keltiruvchi."),
    NameModel(arabic: "الباقي", name: "Al-Bāqi", desc: "Boqiy qoluvchi. U doimiy bordir, unga foniylik oriz boʻlmas."),
    NameModel(arabic: "الوارث", name: "Al-Varis", desc: "Muvjudotlar yoʻq boʻlganda ham boqiy qoluvchi zot."),
    NameModel(arabic: "الرشيد", name: "Ar-Roshīd", desc: "Toʻgʻri yoʻlga irshod qiluvchi."),
    NameModel(arabic: "الصبور", name: "As-Sobur", desc: "Oʻta sabrli. Osiylarni azoblashga shoshilmaydi."),
    
    
  ];
}